CREATE TABLE IF NOT EXISTS `feeds` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `title` varchar(255),
    `label` varchar(255),
    `content` text,
    `insert_link_text` varchar(255),
    `insert_link_url` varchar(255),
    `status_enum` varchar(20),
    `from_date` timestamp,
    `expire_date` timestamp,
    `language` varchar(50),
    `segment_filters` text,
    `in_app` tinyint(1),
    `standalone` tinyint(1),
    `push` tinyint(1),
    `email` tinyint(1),
    `topbar` tinyint(1),
    `popup` tinyint(1),
    `snippet` tinyint(1),
    `tooltip` tinyint(1),
    `enable_comments` tinyint(1),
    `enable_social_media` tinyint(1),
    `enable_reaction` tinyint(1),
    `pin_to_top` tinyint(1),
    `open_link_in_new_tab` tinyint(1),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
